services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "tu_usuario_seguro"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "tu_contraseña_segura"
      - key: N8N_HOST
        value: "n8n.onrender.com"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: NODE_ENV
        value: "production"
      - key: GENERIC_TIMEZONE
        value: "America/Caracas"
